<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<OutDir>..\..\bin\$(Configuration)\net7.0-windows\Notifier\</OutDir>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>   
    <UseWindowsForms>true</UseWindowsForms>
	<AssemblyName>PizzaOven+ Notifier</AssemblyName>
	<Product>PizzaOven+ Notifier</Product>
	<Company>SurfyCrescent97 (Notification App)</Company>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="PizzaOvenPLUSIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>